# -*- coding: utf-8 -*-
"""Trabalho.saje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XY5dsYDi3dlRTznznaZD-2VybkeMIIF-
"""

# Lista de registros
dados = [
    "32.5C,85%",
    "28C,70%",
    "40C,95%",
    "15C,50%",
    "50C,30%",   # temperatura inválida
    "30C,110%",  # umidade inválida
    "abc"         # dado corrompido
]

# Converter Celsius para Fahrenheit
def celsius_para_fahrenheit(c):
    return (c * 9/5) + 32

# Classificar sensação térmica
def sensacao(temp, umidade):
    if temp >= 35 and umidade >= 80:
        return "Muito Quente"
    elif temp >= 30:
        return "Quente"
    elif temp >= 20:
        return "Agradável"
    else:
        return "Frio"

validos = 0
invalidos = 0

print("=== RELATÓRIO CLIMÁTICO ===\n")

for registro in dados:
    try:
        partes = registro.split(",")

        temperatura = float(partes[0].replace("C", ""))
        umidade = int(partes[1].replace("%", ""))

        # Validação
        if not (0 <= temperatura <= 45):
            raise ValueError("Temperatura fora da faixa")

        if not (0 <= umidade <= 100):
            raise ValueError("Umidade fora da faixa")

        fahrenheit = celsius_para_fahrenheit(temperatura)
        classificacao = sensacao(temperatura, umidade)

        print(f"Registro: {registro}")
        print(f"Temperatura: {temperatura:.1f}°C")
        print(f"Fahrenheit: {fahrenheit:.1f}°F")
        print(f"Umidade: {umidade}%")
        print(f"Sensação: {classificacao}")
        print("-" * 30)

        validos += 1

    except:
        print(f"Registro inválido: {registro}")
        print("-" * 30)
        invalidos += 1

print("\n=== RESUMO DO DIA ===")
print(f"Registros válidos: {validos}")
print(f"Registros inválidos: {invalidos}")

# Lista de dados da estação meteorológica
dados = [
    "32.5C,85%",
    "40C,70%",
    "abc,90%",
    "25C,110%",
    "18C,60%"
]

# Percorre cada registro da lista
for registro in dados:
    try:
        # Divide a temperatura e a umidade
        temp, umid = registro.split(",")

        # Remove "C" e converte para número
        temp = float(temp.replace("C", ""))

        # Remove "%" e converte para número
        umid = int(umid.replace("%", ""))

        # Verifica se os valores estão dentro da faixa permitida
        if temp < -10 or temp > 50 or umid < 0 or umid > 100:
            print(registro, "-> Dados inválidos")
            continue  # Pula para o próximo registro

        # Converte a temperatura para Fahrenheit
        fah = temp * 9/5 + 32

        # Classifica a sensação térmica
        if temp >= 35:
            sensacao = "Muito quente"
        elif temp >= 25:
            sensacao = "Quente"
        elif temp >= 15:
            sensacao = "Agradável"
        else:
            sensacao = "Frio"

        # Mostra o resumo do registro
        print(f"{temp}°C = {fah:.1f}°F | Umidade: {umid}% | {sensacao}")

    # Caso ocorra erro na leitura dos dados
    except:
        print(registro, "-> Erro nos dados")